export const HEROES_LIST_REQUEST = 'HEROES_LIST_REQUEST';
export const HEROES_LIST_FETCHING = 'HEROES_LIST_FETCHING';
export const HEROES_LIST_SUCCESS = 'HEROES_LIST_SUCCESS';
export const HEROES_LIST_FAILURE = 'HEROES_LIST_FAILURE';